#!/bin/sh
#PBS -S /bin/sh
#PBS -N mcmc_codecs
#PBS -j oe
#PBS -l nodes=n15:ppn=8,walltime=12:00:00
#PBS -M santiago.casas@cea.fr

module () {
  eval $(/usr/bin/modulecmd bash $*)
}

module load intelpython/3-2020.2

cd /n06data/casas/looti-test-public
echo "activating environment"
source activate lootiemu

echo "installing code"
python setup.py install
echo "running script"

cd notebooks/

python emcee_run_codecs.py | tee mcmc_codecs.log

echo "finished script"
exit 0
