###DATA FORMAT###

datafolder: ../../SimulationData/F_R_Peaks/ #Name of the folder which contains all the data
feature_filename: Peaks_KN_s1_b020_  #Beginning of the file's name without the redshift
filename_format: txt # extension   ## put the dot here, like .txt
LCDM_mode: False #
LCDM_folder:  # Indicate the name of the LCDM folder please
use_reference: False
reference_folder: 

## Position of the columns in the data to be read
grid_pos: 0
feature_pos: 1

## Name of the parameters to be emulated
param_str_array:
- logfR0
- mv

sep_param: _
sep_param_value:

### Data location
starting_row: 0 #at which row the data start
end_row:
redshift_digit: 5 #how many digit for the redshift in the files' names ?
redshift_in_header: True # re redshift in the file name ?
